import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/auth_context";
import { AdminProvider } from "./context/admin_context";
import { CategoryProvider } from "./context/category_context";
import { CartProvider } from "./context/cart_context";
import { OrderProvider } from "./context/order_context";
import { ProductProvider } from "./context/product_context";
import { ConfirmProvider } from "./context/confirm_context";
import { AddressProvider } from "./context/address_context";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Ishop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >  <ConfirmProvider>
          <AuthProvider>
            <AddressProvider>
              <AdminProvider>
                <CategoryProvider>
                  <CartProvider>
                    <OrderProvider >
                      <ProductProvider>

                        {children}
                        <Toaster
                          position="top-center"
                          toastOptions={{
                            duration: 3000,
                            style: {
                              background: '#18181b', // zinc-900
                              color: '#fff',
                              borderRadius: '1rem',
                              border: '1px solid #27272a', // zinc-800
                            },
                          }}
                        />
                      </ProductProvider>
                    </OrderProvider>
                  </CartProvider>
                </CategoryProvider>
              </AdminProvider>
            </AddressProvider>
          </AuthProvider>
        </ConfirmProvider>
      </body>
    </html>
  );
}
