import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/auth_context";
import { AdminProvider } from "./context/admin_context";
import { CategoryProvider } from "./context/category_context";
import { CartProvider } from "./context/cart_context";
import { OrderProvider } from "./context/order_context";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Ishop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <AuthProvider> <AdminProvider>  <CategoryProvider>  <CartProvider>  <OrderProvider > {children}</OrderProvider> </CartProvider> </CategoryProvider>  </AdminProvider> </AuthProvider>
      </body>
    </html>
  );
}
