import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/auth_context";
import { CategoryProvider } from "./context/category_context";
import { CartProvider } from "./context/cart_context";
import { OrderProvider } from "./context/order_context";
import { ConfirmProvider } from "./context/confirm_context";
import { AddressProvider } from "./context/address_context";
import { WishlistProvider } from "./context/wishlist_context";
import { SettingsProvider } from "./context/settings_context";
import RouterInitializer from "./components/RouterInitializer";
import ThemedToaster from "./components/ThemedToaster";
import ThemeProvider from "./components/ThemeProvider";
import PhoneSetupModal from "./components/PhoneSetupModal";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ishop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        <ThemeProvider>
          <SettingsProvider>
            <ConfirmProvider>
              <AuthProvider>
                <AddressProvider>
                  <CategoryProvider>
                    <CartProvider>
                      <OrderProvider>
                        <WishlistProvider>
                          <RouterInitializer />
                          <PhoneSetupModal />
                          {children}
                          <ThemedToaster />
                        </WishlistProvider>
                      </OrderProvider>
                    </CartProvider>
                  </CategoryProvider>
                </AddressProvider>
              </AuthProvider>
            </ConfirmProvider>
          </SettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
