-- CreateTable
CREATE TABLE "FCM" (
    "id" SERIAL NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP(3),
    "userId" INTEGER NOT NULL,

    CONSTRAINT "FCM_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "FCM" ADD CONSTRAINT "FCM_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
